config/routes.rb
SampleApp::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
             controllers: {
             }
  devise_for :re_users, path: 're/users',
             controllers: {
                 registrations: 're_users/registrations',
                 passwords: 're_users/passwords',
                 sessions: 're_users/sessions'
             }
  resources :skills, except: [:index]
  resources :re_skills, path: 're/skills', except: [:index]
  resources :musics do
    collection do
      get 'hot'
      get 'other'
    end
  end
  resources :re_musics, path: 're/musics' do
    collection do
      get 'hot'
      get 'other'
    end
  end
  match '/users/old', to: 'users#index_old', via: 'get'
  resources :users do
    member do
      get 'drum'
      get 'guitar'
      get 'manage'
      post 'import'
    end
  end
  match '/users/old', to: 're_users#index_old', via: 'get'
  resources :re_users, path: 're/users' do
    member do
      get 'drum'
      get 'guitar'
      get 'manage'
      post 'import'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/re', to: 'static_pages#re_home', via: 'get'
  match '/update_maxuser', to: 'skills#update_maxuser', via: 'get'
  match '/api/userlist', to: 'users#userlist', via: 'get'
  devise_scope :user do
    match '/sessions/new.user', to: 'devise/sessions#new', via: :get
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  devise_scope :re_user do
    match '/sessions/new.re_user', to: 're_users/sessions#new', via: :get
    match '/sessions/re_user', to: 're_users/sessions#create', via: :post
  end

  match '/average' => 'static_pages#average', via: :get
  match '/average/drum/other/:from/:to' => 'users#drum_average_other', via: :get
  match '/average/drum/hot/:from/:to' => 'users#drum_average_hot', via: :get
  match '/average/guitar/other/:from/:to' => 'users#guitar_average_other', via: :get
  match '/average/guitar/hot/:from/:to' => 'users#guitar_average_hot', via: :get

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def re_home
    render :layout => 're_application'
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/average.html.erb
<% provide(:title, 'SKILL AVERAGE (β)') %>

<h1>SKILL AVERAGE (β) </h1>

表示に多少時間が掛かります。

<h2>Drummania</h2>

<table class="table table-bordered table-hover table-condensed display compact">
  <thead>
  <tr>
    <th>Hot</th>
    <th>Other</th>
  </tr>
  </thead>

  <tbody>
  <% n = 4000 %>
    <% while n < 9200 %>
      <tr>
        <td><%= link_to "SP #{n} 〜 #{n+200} (Hot)", "/average/drum/hot/#{n}/#{n+200}" %></td>
        <td><%= link_to "SP #{n} 〜 #{n+200} (Other)", "/average/drum/other/#{n}/#{n+200}" %></td>
      </tr>
      <% n+= 200 %>
      <% end %>
  </tbody>
</table>

<h2>GuitarFreaks</h2>

<table class="table table-responsive table-bordered table-hover table-condensed display compact">
  <thead>
  <tr>
    <th>Hot</th>
    <th>Other</th>
  </tr>
  </thead>

  <tbody>
  <% n = 4000 %>
  <% while n < 9200 %>
      <tr>
        <td><%= link_to "SP #{n} 〜 #{n+200} (Hot)", "/average/guitar/hot/#{n}/#{n+200}" %></td>
        <td><%= link_to "SP #{n} 〜 #{n+200} (Other)", "/average/guitar/other/#{n}/#{n+200}" %></td>
      </tr>
      <% n+= 200 %>
  <% end %>
  </tbody>
</table>

app/views/static_pages/help.html.erb
<% provide(:title, 'ヘルプ') %>
    <h1>使い方</h1>
    <p>
    使い方説明
    </p>

app/views/static_pages/home.html.erb
<h1>GITADORA Tri-boost スキルシミュレータ</h1>

<h2>これ何？</h2>
<p>GITADORA Tri-boost
  用スキルシミュレータです。 <%= link_to "GuitarFreaks & DrumMania Skill Simulator", "http://xv-s.heteml.jp/skill/", :target => ["_blank"] %>
  が今作になってから活動を停止しており、スキル表を共有する手立てがなくなったため、勉強がてら作成しました (非公認)。</p>

<h2>スキル表の例</h2>
<%= link_to "DM", drum_user_path(1) %>, <%= link_to "GF", guitar_user_path(1) %>

<h2>ログイン、新規登録</h2>
<p><%= link_to "ログイン", new_user_session_path %> または <%= link_to "新規登録", new_user_registration_path %> はこちら。</p>

<h2>MAX SKILL(理論値スキル計算)</h2>
<p><%= link_to "DM", drum_user_path(3) %>, <%= link_to "GF", guitar_user_path(3) %> <p>

<h2>SKILL AVERAGE (β)</h2>
<p><%= link_to "SKILL AVERAGE (β)", "/average" %></p>

<h2>ユーザ検索</h2>
<p>とりあえず <%= link_to "ユーザ一覧", users_path %> で名前の検索やスキルポイントでの並び替え等はできます。</p>
<p>IE など一部のブラウザでうまく表示されないようなので、暫定的に<%= link_to "旧ユーザー一覧", "/users/old" %>を復活させました。（表示に時間が掛かります）</p>

<h2>開発者の方へ</h2>
<p>ソースコードは <%= link_to "GitHub", "https://github.com/kumamotone/gfdm-skill", :target => ["_blank"] %>
  上で公開しています。ぜひ開発にご参加ください。 issue も歓迎です。</p>

<h2>リンク</h2>
<ul>
  <li><%= link_to "BEMANIWiki 2nd", "http://bemaniwiki.com/index.php?GITADORA%20Tri-Boost", :target => ["_blank"] %> </li>
  <li><%= link_to "eAMUSEMENT プレーデータ", "http://p.eagate.573.jp/game/gfdm/gitadora_tb/p/eam/index.html", :target => ["_blank"] %></li>
</ul>

<h2>更新情報、連絡先</h2>
<p>更新情報、障害情報などに関しては基本的に Twitterアカウントでお知らせする予定ですが、長くなる場合は <%= link_to "更新情報ブログ", "http://gfdmskill.blog.fc2.com/", :target => ["_blank"] %> に詳しく書くのでご確認ください。不具合や曲情報の間違いなどは、コメント欄などでお知らせください。</p>

<a class="twitter-timeline" data-width="400" data-height="600" href="https://twitter.com/gfdmskill">Tweets by gfdmskill</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

app/views/static_pages/re_home.html.erb
<h1>GITADORA Tri-boost Re:EVOLVE スキルシミュレータ</h1>

<h2>これ何？</h2>
<p>GITADORA Tri-boost
  用スキルシミュレータです。 <%= link_to "GuitarFreaks & DrumMania Skill Simulator", "http://xv-s.heteml.jp/skill/", :target => ["_blank"] %>
  が今作になってから活動を停止しており、スキル表を共有する手立てがなくなったため、勉強がてら作成しました (非公認)。</p>

<h2>スキル表の例</h2>
<%= link_to "DM", drum_user_path(1) %>, <%= link_to "GF", guitar_user_path(1) %>

<h2>ログイン、新規登録</h2>
<p><%= link_to "ログイン", new_user_session_path %> または <%= link_to "新規登録", new_user_registration_path %> はこちら。</p>

<h2>MAX SKILL(理論値スキル計算)</h2>
<p><%= link_to "DM", drum_user_path(3) %>, <%= link_to "GF", guitar_user_path(3) %> <p>

<h2>SKILL AVERAGE (β)</h2>
<p><%= link_to "SKILL AVERAGE (β)", "/average" %></p>

<h2>ユーザ検索</h2>
<p>とりあえず <%= link_to "ユーザ一覧", users_path %> で名前の検索やスキルポイントでの並び替え等はできます。</p>
<p>IE など一部のブラウザでうまく表示されないようなので、暫定的に<%= link_to "旧ユーザー一覧", "/users/old" %>を復活させました。（表示に時間が掛かります）</p>

<h2>開発者の方へ</h2>
<p>ソースコードは <%= link_to "GitHub", "https://github.com/kumamotone/gfdm-skill", :target => ["_blank"] %>
  上で公開しています。ぜひ開発にご参加ください。 issue も歓迎です。</p>

<h2>リンク</h2>
<ul>
  <li><%= link_to "BEMANIWiki 2nd", "http://bemaniwiki.com/index.php?GITADORA%20Tri-Boost", :target => ["_blank"] %> </li>
  <li><%= link_to "eAMUSEMENT プレーデータ", "http://p.eagate.573.jp/game/gfdm/gitadora_tb/p/eam/index.html", :target => ["_blank"] %></li>
</ul>

<h2>更新情報、連絡先</h2>
<p>更新情報、障害情報などに関しては基本的に Twitterアカウントでお知らせする予定ですが、長くなる場合は <%= link_to "更新情報ブログ", "http://gfdmskill.blog.fc2.com/", :target => ["_blank"] %> に詳しく書くのでご確認ください。不具合や曲情報の間違いなどは、コメント欄などでお知らせください。</p>

<a class="twitter-timeline" data-width="400" data-height="600" href="https://twitter.com/gfdmskill">Tweets by gfdmskill</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>