config/routes.rb
SampleApp::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
             controllers: {
             }
  devise_for :re_users, path: 're/users',
             controllers: {
                 registrations: 're_users/registrations',
                 passwords: 're_users/passwords',
                 sessions: 're_users/sessions'
             }
  resources :skills, except: [:index]
  resources :re_skills, path: 're/skills', except: [:index]
  resources :musics do
    collection do
      get 'hot'
      get 'other'
    end
  end
  resources :re_musics, path: 're/musics' do
    collection do
      get 'hot'
      get 'other'
    end
  end
  match '/users/old', to: 'users#index_old', via: 'get'
  resources :users do
    member do
      get 'drum'
      get 'guitar'
      get 'manage'
      post 'import'
    end
  end
  match '/users/old', to: 're_users#index_old', via: 'get'
  resources :re_users, path: 're/users' do
    member do
      get 'drum'
      get 'guitar'
      get 'manage'
      post 'import'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/re', to: 'static_pages#re_home', via: 'get'
  match '/update_maxuser', to: 'skills#update_maxuser', via: 'get'
  match '/api/userlist', to: 'users#userlist', via: 'get'
  devise_scope :user do
    match '/sessions/new.user', to: 'devise/sessions#new', via: :get
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  devise_scope :re_user do
    match '/sessions/new.re_user', to: 're_users/sessions#new', via: :get
    match '/sessions/re_user', to: 're_users/sessions#create', via: :post
  end

  match '/average' => 'static_pages#average', via: :get
  match '/average/drum/other/:from/:to' => 'users#drum_average_other', via: :get
  match '/average/drum/hot/:from/:to' => 'users#drum_average_hot', via: :get
  match '/average/guitar/other/:from/:to' => 'users#guitar_average_other', via: :get
  match '/average/guitar/hot/:from/:to' => 'users#guitar_average_hot', via: :get

end

app/models/re_music.rb
class ReMusic < ActiveRecord::Base
  has_many :re_skill, dependent: :destroy
  validates_inclusion_of :ishot, :in => [true, false]
  validates :d_bsc, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9.99}
  validates :d_adv, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9.99}
  validates :d_ext, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9.99}
  validates :d_mas, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9.99}

  validates :g_bsc, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9.99}
  validates :g_adv, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9.99}
  validates :g_ext, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9.99}
  validates :g_mas, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9.99}

  validates :b_bsc, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9.99}
  validates :b_adv, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9.99}
  validates :b_ext, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9.99}
  validates :b_mas, presence: true, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 9.99}
end

app/controllers/re_musics_controller.rb
class ReMusicsController < ApplicationController
  layout 're_application'
  #before_action :signed_in_user,     only: [:edit, :update, :create, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :create, :destroy]
  before_action :admin_user, only: [:edit, :update, :create, :destroy]

  # GET /Remusics
  # GET /Remusics.json
  def index
  end

  def show
    @music = ReMusic.find(params[:id])
  end

  def hot
    @musics = ReMusic.all.where(ishot: true)
  end

  def other
    @musics = ReMusic.all.where(ishot: false)
  end

  def new
    @music = ReMusic.new
  end

  def edit
    @music = ReMusic.find(params[:id])
  end

  def destroy
    entry = ReNusic.find(params[:id])
    client = ApplicationController.helpers.get_twitter_client

    tweet_text = "曲情報が削除されました。(by @#{current_re_user.twitterid}) \n\n削除曲: #{entry.name}"
    if Rails.env == 'development'
      tweet_text = tweet_text + "(開発テスト)"
    end
    client.update(tweet_text)
    entry.destroy

    ApplicationController.helpers.create_max
    flash[:success] = "曲情報を削除しました．"
    redirect_to re_path
  end

  def update
    @music = ReMusic.find(params[:id])
    @music.name.strip! unless @music.name.nil?

    # 本当はここでこれを登録しているスキルのSPを更新するとかしたほうがいい
    if @music.update_attributes(music_params)
      client = ApplicationController.helpers.get_twitter_client

      # スクリーンネームは最大15文字なので、曲名は39文字に削る
      # (一番長いと思われる 轟け!恋のビーンボール!! ～96バット砲炸裂!GITADORAシリーズMVP弾!～ で42文字なので稀に切れるはず)
      # Rails に truncate という便利ヘルパーがあるのでそれ使った方が良いかも
      tweet_text = "曲情報が変更されました。(by @%s) \n\n%.39s\nD %.2f %.2f %.2f %.2f\nG %.2f %.2f %.2f %.2f\nB %.2f %.2f %.2f %.2f" % [current_re_user.twitterid , @music.name, @music.d_bsc, @music.d_adv, @music.d_ext, @music.d_mas, @music.g_bsc, @music.g_adv, @music.g_ext, @music.g_mas, @music.b_bsc, @music.b_adv, @music.b_ext, @music.b_mas]
      if Rails.env == 'development'
        tweet_text = tweet_text + "(開発テスト)"
      end
      client.update(tweet_text)

      ApplicationController.helpers.create_max

      flash[:success] = "曲情報を更新しました．"
      redirect_to re_path
    else
      render 'edit'
    end
  end

  def create
    @music = ReMusic.new(music_params)
    @music.id = ReMusic.maximum(:id).next  # 最大の番号が削除済みの場合連番にならなくなってしまうので調整
    @music.name.strip! unless @music.name.nil?

    if @music.save
      client = ApplicationController.helpers.get_twitter_client
      # スクリーンネームは最大15文字なので、曲名は39文字に削る
      # (一番長いと思われる 轟け!恋のビーンボール!! ～96バット砲炸裂!GITADORAシリーズMVP弾!～ で42文字なので稀に切れるはず)
      # Rails に truncate という便利ヘルパーがあるのでそれ使った方が良いかも
      tweet_text = "曲情報が追加されました。(by @%s) \n\n%.39s\nD %.2f %.2f %.2f %.2f\nG %.2f %.2f %.2f %.2f\nB %.2f %.2f %.2f %.2f" % [current_re_user.twitterid , @music.name, @music.d_bsc, @music.d_adv, @music.d_ext, @music.d_mas, @music.g_bsc, @music.g_adv, @music.g_ext, @music.g_mas, @music.b_bsc, @music.b_adv, @music.b_ext, @music.b_mas]
      if Rails.env == 'development'
        tweet_text = tweet_text + "(開発テスト)"
      end
      client.update(tweet_text)

      ApplicationController.helpers.create_max
      flash[:success] = "曲情報が追加されました！"
      redirect_to re_path
    else
      render 'new'
    end
  end

  def musiclist
    users = ReUser.all
    array = []
    users.each {|user|
      array.push([user.id, user.name, user.d, user.g, user.skill_updated_at_d, user.skill_updated_at_g])
    }
    render :json => { :users => array.as_json }
  end

  private

  def music_params
    params.require(:re_music).permit(:name, :bpm, :d_bsc, :d_adv, :d_ext, :d_mas,
                                  :g_bsc, :g_adv, :g_ext, :g_mas, :b_bsc, :b_adv, :b_ext, :b_mas, :ishot)
  end

  # Before actions

  #def signed_in_user
  #  unless signed_in?
  #    store_location
  #    redirect_to signin_url, notice: "Please sign in."
  #  end
  #end

  def admin_user
    if current_re_user.admin? || current_re_user.subadmin?
      # pass
    else
      flash[:error] = "曲情報を変更する権限がありません。"
      redirect_to(re_path)
    end
  end
end

app/views/re_musics/_contents.html.erb
<table id="sTable_musics" class="table table-striped table-bordered table-hover table-condensed display compact">
  <thead>
  <tr>
    <th rowspan="2">Name</th>
    <th colspan="4">Drum</th>
    <th colspan="4">Guitar</th>
    <th colspan="4">Bass</th>
    <% if !current_user.nil? && (current_user.admin? || current_user.subadmin?) then %>
        <th rowspan="2">id</th>
    <% end %>
  </tr>
  <tr>
    <th>BSC</th>
    <th>ADV</th>
    <th>EXT</th>
    <th>MAS</th>
    <th>BSC</th>
    <th>ADV</th>
    <th>EXT</th>
    <th>MAS</th>
    <th>BSC</th>
    <th>ADV</th>
    <th>EXT</th>
    <th>MAS</th>
  </tr>
  </thead>

  <tbody>
  <% @musics.each do |music| %>
      <% unless music.name.include?("汎用") %>
      <tr data-music_id="<%= music.id %>">
        <td><%= music.name %></td>
        <td><%= if music.d_bsc != 0.0
                  number_with_precision music.d_bsc, precision: 2
                else
                  "-"
                end %></td>
        <td><%= if music.d_adv != 0.0
                  number_with_precision music.d_adv, precision: 2
                else
                  "-"
                end %></td>
        <td><%= if music.d_ext != 0.0
                  number_with_precision music.d_ext, precision: 2
                else
                  "-"
                end %></td>
        <td>
          <%= if music.d_mas != 0.0
                number_with_precision music.d_mas, precision: 2
              else
                "-"
              end %>
        </td>
        <td>
          <%= if music.g_bsc != 0.0
                number_with_precision music.g_bsc, precision: 2
              else
                "-"
              end %></td>
        <td><%= if music.g_adv != 0.0
                  number_with_precision music.g_adv, precision: 2
                else
                  "-"
                end %></td>
        <td><%= if music.g_ext != 0.0
                  number_with_precision music.g_ext, precision: 2
                else
                  "-"
                end %></td>
        <td><%= if music.g_mas != 0.0
                  number_with_precision music.g_mas, precision: 2
                else
                  "-"
                end %></td>
        <td><%= if music.b_bsc != 0.0
                  number_with_precision music.b_bsc, precision: 2
                else
                  "-"
                end %></td>
        <td><%= if music.b_adv != 0.0
                  number_with_precision music.b_adv, precision: 2
                else
                  "-"
                end %></td>
        <td><%= if music.b_ext != 0.0
                  number_with_precision music.b_ext, precision: 2
                else
                  "-"
                end %></td>
        <td><%= if music.b_mas != 0.0
                  number_with_precision music.b_mas, precision: 2
                else
                  "-"
                end %></td>
        <% if !current_user.nil? && (current_user.admin? || current_user.subadmin?) then %>
          <td><%= link_to music.id, edit_music_path(music) %></td>
        <% end %>
      </tr>
      <% end %>
  <% end %>
  </tbody>
</table>

app/views/re_musics/_form.html.erb
<div class="row">
  <div class="form-horizontal" role="form">
    <%= form_for(@music) do |s| %>
        <%= render 'shared/error_messages', object: s.object %>

        <div class="form-group">
          <%= s.label :name, "曲名", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :name, placeholder: "前後の空白は登録時に取り除かれます", class: "form-control" %>
          </div>
        </div>

        <!--<div class="form-group">-->
          <!--<%= s.label :bpm, "BPM", :class => "col-sm-3 control-label" %>-->
          <!--<div class="col-sm-6">-->
            <!--<%= s.text_field :bpm, placeholder: "string (なくても登録できます)", class: "form-control" %>-->
          <!--</div>-->
        <!--</div>-->

        <% if mode == "new" then %>
        <div class="form-group">
          <div class="col-sm-3 control-label">難易値簡単入力フォーム</div>
          <div class="col-sm-4">
            <input class="form-control" placeholder="12個のスペース区切りの数値を入力できます" type="text" id="benry">
          </div>
          <div class="col-sm-2">
            <button type="button" id="benrybtn">値をセット</button>
          </div>
        </div>
        <% end %>

        <div class="form-group">
          <%= s.label :d_bsc, "D_BSC", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :d_bsc, placeholder: "float", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= s.label :d_adv, "D_ADV", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :d_adv, placeholder: "float", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= s.label :d_ext, "D_EXT", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :d_ext, placeholder: "float", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= s.label :d_mas, "D_MAS", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :d_mas, placeholder: "float", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= s.label :g_bsc, "G_BSC", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :g_bsc, placeholder: "float", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= s.label :g_adv, "G_ADV", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :g_adv, placeholder: "float", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= s.label :g_ext, "G_EXT", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :g_ext, placeholder: "float", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= s.label :g_mas, "G_MAS", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :g_mas, placeholder: "float", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= s.label :b_bsc, "B_BSC(ない場合は0を入力)", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :b_bsc, placeholder: "float", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= s.label :b_adv, "B_ADV(ない場合は0を入力)", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :b_adv, placeholder: "float", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= s.label :b_ext, "B_EXT(ない場合は0を入力)", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :b_ext, placeholder: "float", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= s.label :b_mas, "B_MAS(ない場合は0を入力)", :class => "col-sm-3 control-label" %>
          <div class="col-sm-6">
            <%= s.text_field :b_mas, placeholder: "float", class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= s.label :ishot, "HOT?", :class => "col-sm-3 control-label" %>
          <div class="col-sm-offset-3 col-sm-6 col-xs-offset-1">
            <div class="checkbox">
              <% if mode == "edit" then %>
                <%= s.check_box :ishot %></div>
              <% elsif mode == "new" %>
                <%= s.check_box :ishot, {:checked => true} %></div>
              <% end %>
        </div>

        </div>

        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-6">
            <% if mode == "edit" then %>
                <%= s.submit "編集(多少時間が掛かります)", class: "btn btn-large btn-primary" %>
            <% elsif mode == "new" %>
              <%= s.submit "登録(多少時間が掛かります)", class: "btn btn-large btn-primary" %>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/re_musics/edit.html.erb
<h1>曲編集</h1>

<%= render partial: "form", locals: {mode: "edit"} %>
<%= link_to "削除", @re_music, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn btn-danger" %>

app/views/re_musics/hot.html.erb
<% provide(:title, '曲一覧 - Hot') %>
<h1>曲一覧</h1>

<h2>Hot</h2>
<%= render 'contents' %>

app/views/re_musics/index.html.erb
<% provide(:title, '曲一覧') %>
<h1>曲一覧</h1>

<h2><%= link_to "Hot の曲一覧", hot_re_musics_path %></h2>
<h2><%= link_to "Other の曲一覧", other_re_musics_path %></h2>

app/views/re_musics/new.html.erb
<% provide(:title, '曲登録') %>
<h1>曲登録</h1>

<%= render partial: "form", locals: {mode: "new"} %>

app/views/re_musics/other.html.erb
<% provide(:title, '曲一覧 - Other') %>
<h1>曲一覧</h1>
    <h2>Other</h2>
<%= render 'contents' %>

app/views/re_musics/show.html.erb
いちおう作成