config/routes.rb
SampleApp::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users,
             controllers: {
             }
  devise_for :re_users, path: 're/users',
             controllers: {
                 registrations: 're_users/registrations',
                 passwords: 're_users/passwords',
                 sessions: 're_users/sessions'
             }
  resources :skills, except: [:index]
  resources :re_skills, path: 're/skills', except: [:index]
  resources :musics do
    collection do
      get 'hot'
      get 'other'
    end
  end
  resources :re_musics, path: 're/musics' do
    collection do
      get 'hot'
      get 'other'
    end
  end
  match '/users/old', to: 'users#index_old', via: 'get'
  resources :users do
    member do
      get 'drum'
      get 'guitar'
      get 'manage'
      post 'import'
    end
  end
  match '/users/old', to: 're_users#index_old', via: 'get'
  resources :re_users, path: 're/users' do
    member do
      get 'drum'
      get 'guitar'
      get 'manage'
      post 'import'
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match '/re', to: 'static_pages#re_home', via: 'get'
  match '/update_maxuser', to: 'skills#update_maxuser', via: 'get'
  match '/api/userlist', to: 'users#userlist', via: 'get'
  devise_scope :user do
    match '/sessions/new.user', to: 'devise/sessions#new', via: :get
    match '/sessions/user', to: 'devise/sessions#create', via: :post
  end

  devise_scope :re_user do
    match '/sessions/new.re_user', to: 're_users/sessions#new', via: :get
    match '/sessions/re_user', to: 're_users/sessions#create', via: :post
  end

  match '/average' => 'static_pages#average', via: :get
  match '/average/drum/other/:from/:to' => 'users#drum_average_other', via: :get
  match '/average/drum/hot/:from/:to' => 'users#drum_average_hot', via: :get
  match '/average/guitar/other/:from/:to' => 'users#guitar_average_other', via: :get
  match '/average/guitar/hot/:from/:to' => 'users#guitar_average_hot', via: :get

end

app/controllers/re_users/confirmations_controller.rb
class ReUsers::ConfirmationsController < Devise::ConfirmationsController
  layout 're_application'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/re_users/omniauth_callbacks_controller.rb
class ReUsers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  layout 're_application'
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/re_users/passwords_controller.rb
class ReUsers::PasswordsController < Devise::PasswordsController
  layout 're_application'
  
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/re_users/registrations_controller.rb
class ReUsers::RegistrationsController < Devise::RegistrationsController
  layout 're_application'
  # before_filter :configure_sign_up_params, only: [:create]
  # before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.for(:sign_up) << :attribute
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.for(:account_update) << :attribute
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/re_users/sessions_controller.rb
class ReUsers::SessionsController < Devise::SessionsController
  layout 're_application'
  # before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/re_users/unlocks_controller.rb
class ReUsers::UnlocksController < Devise::UnlocksController
  layout 're_application'
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/re_users_controller.rb
class ReUsersController < ApplicationController
  layout 're_application'
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :manage, :import]
  # before_action :correct_user,   only: [:edit, :update, :manage, :import]
  before_action :admin_user, only: :destroy

  def index
    @users = ReUser.all
  end

  def index_old
    @users = ReUser.all
  end

  def import
    @user = ReUser.find(params[:id])
    if params[:csv_file].blank?
      redirect_to(@user, alert: 'インポートするCSVファイルを選択してください')
    else
      num = ReSkill.import(params[:csv_file], @user.id)
      redirect_to(@user, notice: "#{num.to_s} 件のスキルを追加 / 更新しました")
    end
  end

  def manage
  end

  def show
    @user = ReUser.find(params[:id])

    respond_to do |format|
      format.html
      format.csv { send_data @user.re_skills.to_csv }
    end
  end

  def drum
    @user = ReUser.find(params[:id])

    @hot= @user.re_skills.find_by_sql(['SELECT s.*
                                     FROM re_skills AS s
                                     WHERE s.re_user_id = ? AND
                                          (s.re_music_id >= 712) AND
                                          (s.kind BETWEEN 0 AND 3)
                                     AND NOT EXISTS
                                        ( SELECT 1 FROM skills AS t
                                          WHERE s.re_music_id = t.re_music_id AND
                                                s.re_user_id = t.re_user_id AND
                                                s.sp < t.sp AND (t.kind BETWEEN 0 AND 3))
                                     ORDER BY sp DESC', @user.id])
    @other = @user.re_skills.find_by_sql(['SELECT s.*
                                     FROM re_skills AS s
                                     WHERE s.re_user_id = ? AND
                                          (s.re_music_id BETWEEN 1 AND 711) AND
                                          (s.kind BETWEEN 0 AND 3)
                                     AND NOT EXISTS
                                        ( SELECT 1 FROM skills AS t
                                          WHERE s.re_music_id = t.re_music_id AND
                                                s.re_user_id = t.re_user_id AND
                                                s.sp < t.sp AND (t.kind BETWEEN 0 AND 3))
                                     ORDER BY sp DESC', @user.id])

    ActiveRecord::Associations::Preloader.new.preload(@hot, :music)
    ActiveRecord::Associations::Preloader.new.preload(@other, :music)
    #@hot = @user.skills.where(music_id: 712..900, kind: 0..3).order("sp DESC").group("music_id").order("sp DESC")
    #@other = @user.skills.where(music_id: 1..711, kind: 0..3).order("sp DESC").group("music_id").order("sp DESC")# 終端位置変更の必要あり

    # 必要な情報をフェッチ
    @hot_sp = @user.dhot
    @other_sp = @user.dother
    @skill_sp = @user.d
    @all_sp = @user.dall
  end

  def guitar
    @user = ReUser.find(params[:id])
    @hot= @user.re_skills.find_by_sql(['SELECT s.*
                                     FROM re_skills AS s
                                     WHERE s.re_user_id = ? AND
                                          (s.re_music_id >= 712) AND
                                          (s.kind BETWEEN 4 AND 11)
                                     AND NOT EXISTS
                                        ( SELECT 1 FROM re_skills AS t
                                          WHERE s.re_music_id = t.re_music_id AND
                                                s.re_user_id = t.re_user_id AND
                                                s.sp < t.sp AND (t.kind BETWEEN 4 AND 11))
                                     ORDER BY sp DESC', @user.id])
    @other = @user.re_skills.find_by_sql(['SELECT s.*
                                     FROM re_skills AS s
                                     WHERE s.re_user_id = ? AND
                                          (s.re_music_id BETWEEN 1 AND 711) AND
                                          (s.kind BETWEEN 4 AND 11)
                                     AND NOT EXISTS
                                        ( SELECT 1 FROM re_skills AS t
                                          WHERE s.re_music_id = t.re_music_id AND
                                                s.re_user_id = t.re_user_id AND
                                                s.sp < t.sp AND (t.kind BETWEEN 4 AND 11))
                                     ORDER BY sp DESC', @user.id])


    ActiveRecord::Associations::Preloader.new.preload(@hot, :music)
    ActiveRecord::Associations::Preloader.new.preload(@other, :music)

    #@hot = @user.skills.where(music_id: 712..900, kind: 4..11).order("sp DESC").group("music_id").order("sp DESC")
    #@other = @user.skills.where(music_id: 1..711, kind: 4..11).order("sp DESC").group("music_id").order("sp DESC") # 終端位置変更の必要あり

    # 必要な情報をフェッチ
    @hot_sp = @user.ghot
    @other_sp = @user.gother
    @skill_sp = @user.g
    @all_sp = @user.gall
  end

  def new
    @user = ReUser.new
  end

  def edit
    @user = ReUser.find(params[:id])
  end

  def destroy
    ReUser.find(params[:id]).destroy
    flash[:success] = "ユーザを削除しました．"
    redirect_to users_url
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィールを更新しました．"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def create
    @user = ReUser.new(user_params)
    @user.id = ReUser.maximum(:id).next # 最大の番号が削除済みの場合連番にならなくなってしまうので調整
    if @user.save
      sign_in @user
      flash[:success] = "アカウントが作成されました！"
      redirect_to @user
    else
      render 'new'
    end
  end

  def userlist
    users = ReUser.all
    array = []
    users.each {|user|
      array.push([user.id, user.name, user.d, user.g, user.skill_updated_at_d, user.skill_updated_at_g])
    }
    render :json => { :users => array.as_json }
  end

  def drum_average_other
    @average = calc_average(true, true)
  end

  def drum_average_hot
    @average = calc_average(true, false)
  end

  def guitar_average_other
    @average = calc_average(false, true)
  end

  def guitar_average_hot
    @average = calc_average(false, false)
  end

  def calc_average(isDrum, isOther)
    from = params[:from]
    to = params[:to]
    max_music_id = ReMusic.maximum(:id)

    if isDrum
      users = ReUser.where(d: from..to)
    else
      users = ReUser.where(g: from..to)
    end

    skills = Hash.new()

    # init
    if isOther
      if isDrum
        1.upto(711){ |i|
          0.upto(3) { |j|
           skills.store([i,j], {"rates" => []})
          }
        }
      else
        1.upto(711){ |i|
          4.upto(11) { |j|
            skills.store([i,j], {"rates" => []})
          }
        }
      end
    else
      if isDrum
        712.upto(max_music_id){ |i|
          0.upto(3) { |j|
            skills.store([i,j], {"rates" => []})
          }
        }
      else
        712.upto(max_music_id){ |i|
          4.upto(11) { |j|
            skills.store([i,j], {"rates" => []})
          }
        }
      end
    end

    if isOther
      users.each { |user|
        if isDrum
          user.re_skills.where(music_id: 1..711, kind: 0..3).each { |skill|
          arr = skills.fetch([skill.music_id,skill.kind])
          rates = arr.fetch("rates")
          rates.push({"rate" => skill.rate, "sp" => skill.sp})
        }
        else
          user.re_skills.where(music_id: 1..711, kind: 4..11).each { |skill|
            arr = skills.fetch([skill.music_id,skill.kind])
            rates = arr.fetch("rates")
            rates.push({"rate" => skill.rate, "sp" => skill.sp})
          }
        end
      }
    else
      if isDrum
        users.each { |user|
        user.re_skills.where(music_id: 712..max_music_id, kind: 0..3).each { |skill|
          arr = skills.fetch([skill.music_id,skill.kind])
          rates = arr.fetch("rates")
          rates.push({"rate" => skill.rate, "sp" => skill.sp})
        }
      }
      else
        users.each { |user|
          user.re_skills.where(music_id: 712..max_music_id, kind: 4..11).each { |skill|
            arr = skills.fetch([skill.music_id,skill.kind])
            rates = arr.fetch("rates")
            rates.push({"rate" => skill.rate, "sp" => skill.sp})
          }
        }
      end
    end

    skills.delete_if {|k, v| v.fetch("rates").size == 0 }
    # skills = skills.sort_by{|k, v| v.fetch("rates").size }.reverse

    returnArr = []

    skills.each { |k,v|
      rates = v.fetch("rates")

      size = rates.size
      # v.store("size", size)

      if size != 0
        ave_rate = rates.inject(0) {|sum, item| sum + item.fetch("rate")} / size
        ave_sp = rates.inject(0) {|sum, item| sum + item.fetch("sp")} / size

        # v.store("ave_rate", ave_rate)
        # v.store("ave_sp", ave_sp)

        music = ReMusic.find_by_id(k[0])
        if music.nil?
          # v.store("name", "deleted")
          returnArr.push([k[0], "deleted", k[1], ave_rate, ave_sp, size])
          return
        else
          # v.store("name", music.name)
          returnArr.push([k[0], music.name, k[1], ave_rate, ave_sp, size])
        end
        # v.store("kind", k[1])
      end
      # v.delete("rates")
    }

    # render :json => skills.as_json
    # render :json => { :aves => returnArr.as_json }
    return returnArr.take(200)  # 表示に時間がかかるので
  end

  private
  def user_params
    params.require(:re_user).permit(:name, :email, :password,
                                 :password_confirmation, :g_comment, :d_comment, :g, :ghot, :gohter, :gall, :d, :dhot, :dother, :dall, :place)
  end

  # Before actions

  #def signed_in_user
  #  unless signed_in?
  #    store_location
  #    redirect_to signin_url, notice: "Please sign in."
  #  end
  #end

  def admin_user
    redirect_to(root_path) unless current_re_user.admin?
  end

  def correct_user
    @user = ReUser.find(params[:id])
    redirect_to re_user_path, notice: "正しいユーザでログインしてください．" unless current_re_user?(@user)
  end

app/controllers/reusers/confirmations_controller.rb
class ReUsers::ConfirmationsController < Devise::ConfirmationsController
  layout 're_application'
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/views/re_users/_averagetable.html.erb
<table id="averageTable" class="table table-bordered table-hover table-condensed display compact">
  <thead>
  <tr>
    <th></th>
    <th>曲名</th>
    <th>レベル</th>
    <th>達成率</th>
    <th>スキル</th>
    <th>登録数</th>
  </tr>
  </thead>

  <tbody>
  <% @average.each do |skill| %>
      <tr class=<%= show_color(skill[2]) %>>
        <td></td>
        <td><%= skill[1] %></td>
        <td><%= number_with_precision(fetch_level_by_id(skill[0], skill[2].to_i), precision: 2) %> <%= show_kind(skill[2]) %></td>
        <td><%= number_with_precision(skill[3], precision: 2) %>% (<%= show_rank(skill[3], false) %>)</td>
        <td><%= number_with_precision(skill[4], precision: 2) %></td>
        <td><%= skill[5] %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/re_users/_skilltable.html.erb
<h2>Hot</h2>
<table id="sortableTable" class="table table-bordered table-hover table-condensed display compact">
  <thead>
  <tr>
    <th></th>
    <th>曲名</th>
    <th>レベル</th>
    <th>達成率</th>
    <th>スキル</th>
    <th>コメント</th>
  </tr>
  </thead>

  <tbody>
  <% @hot.each do |skill| %>
      <tr class=<%= show_color(skill.kind) %>>
        <td></td>
        <td>
          <% if current_re_user == @user %>
              <%= link_to skill.music.name, edit_skill_path(skill) %>
          <% else %>
              <%= skill.music.name %>
          <% end %>
        </td>
        <td><%= number_with_precision(fetch_level(skill.music, skill.kind), precision: 2) %> <%= show_kind(skill.kind) %></td>
        <td><%= number_with_precision(skill.rate, precision: 2) %>% (<%= show_rank(skill.rate, skill.isfc) %>)</td>
        <td><%= link_to number_with_precision(skill.sp, precision: 2), skill_path(skill) %></td>
        <td><%= skill.comment %></td>
      </tr>
  <% end %>
  </tbody>
</table>
<h2>Other</h2>
<table id="sortableTable2" class="table table-responsive table-bordered table-hover table-condensed display compact">
  <thead>
  <tr>
    <th></th>
    <th>曲名</th>
    <th>レベル</th>
    <th>達成率</th>
    <th>スキル</th>
    <th>コメント</th>
  </tr>
  </thead>

  <tbody>
  <% @other.each do |skill| %>
      <tr class=<%= show_color(skill.kind) %>>
        <td></td>
        <td>
          <% if current_re_user == @user %>
              <%= link_to skill.music.name, edit_skill_path(skill) %>
          <% else %>
              <%= skill.music.name %>
          <% end %>
        </td>
        <td><%= number_with_precision(fetch_level(skill.music, skill.kind), precision: 2) %> <%= show_kind(skill.kind) %></td>
        <td><%= number_with_precision(skill.rate, precision: 2) %>% (<%= show_rank(skill.rate, skill.isfc) %>)</td>
        <td><%= link_to number_with_precision(skill.sp, precision: 2), skill_path(skill) %></td>
        <td><%= skill.comment %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/re_users/_sptable.html.erb
最終更新: <%= updated_at %>
<table class="table">
  <thead>
  <tr class="gray">
    <th>Skill</th>
    <th>Hot</th>
    <th>Other</th>
    <th>All</th>
  </tr>
  </thead>
  <tbody>
  <tr class="black">
    <% skillcolor = get_skillcolor(sp) %>
    <td>
      <div class=<%= skillcolor %>><%= number_with_precision sp, precision: 2 %></div>
    </td>
    <td>
      <div class=<%= skillcolor %>><%= number_with_precision hot, precision: 2 %></div>
    </td>
    <td>
      <div class=<%= skillcolor %>><%= number_with_precision other, precision: 2 %></div>
    </td>
    <td>
      <div class=<%= skillcolor %>><%= number_with_precision all, precision: 2 %></div>
    </td>
  </tr>
</table>

app/views/re_users/drum.html.erb
<% provide(:title, @user.name + ' さんのスキル (DrumMania)') %>

<h1>
  <%= @user.name %> さんのスキル (DrumMania)
</h1>

<p><%= link_to "GuitarFreaksスキル表へ", guitar_re_user_path %></p>

<div class="well">
  <%= simple_format @user.d_comment %>
</div>
<%= render partial: 'sptable', locals: {sp: @user.d, hot: @user.dhot, other: @user.dother, all: @user.dall, updated_at: @user.skill_updated_at_d} %>
<%= render 'skilltable' %>

app/views/re_users/drum_average_hot.html.erb
<% provide(:title, "SKILL AVERAGE SP #{params[:from]} 〜 #{params[:to]} (DrumMania)") %>

<h1>
  <%= "SKILL AVERAGE SP #{params[:from]} 〜 #{params[:to]}" %> (DrumMania)
</h1>

<h2>Hot</h2>

<%= render partial: 'averagetable' %>

app/views/re_users/drum_average_other.html.erb
<% provide(:title, "SKILL AVERAGE SP #{params[:from]} 〜 #{params[:to]} (DrumMania)") %>

<h1>
  <%= "SKILL AVERAGE SP #{params[:from]} 〜 #{params[:to]}" %> (DrumMania)
</h1>

<h2>Other</h2>

<%= render partial: 'averagetable' %>

app/views/re_users/edit.html.erb
<!-- devise に移行したため削除しました -->

app/views/re_users/guitar_average_hot.html.erb
<% provide(:title, "SKILL AVERAGE SP #{params[:from]} 〜 #{params[:to]} (GuitarFreaks)") %>

<h1>
  <%= "SKILL AVERAGE SP #{params[:from]} 〜 #{params[:to]}" %> (GuitarFreaks)
</h1>

<h2>Hot</h2>

<%= render partial: 'averagetable' %>

app/views/re_users/guitar_average_other.html.erb
<% provide(:title, "SKILL AVERAGE SP #{params[:from]} 〜 #{params[:to]} (GuitarFreaks)") %>

<h1>
  <%= "SKILL AVERAGE SP #{params[:from]} 〜 #{params[:to]}" %> (GuitarFreaks)
</h1>

<h2>Other</h2>

<%= render partial: 'averagetable' %>

app/views/re_users/index.html.erb
<% provide(:title, 'ユーザ一覧') %>
<h1>ユーザ一覧</h1>

<table id="sTable" class="table table-bordered table-hover table-condensed display compact">
  <thead>
  <tr class="gray">
    <th></th>
    <th width="200">名前</th>
    <th>DM</th>
    <th>GF</th>
    <th>最終更新(DM)</th>
    <th>最終更新(GF)</th>
  </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/re_users/index_old.html.erb
<% provide(:title, 'ユーザ一覧') %>

<h1>ユーザ一覧</h1>

このページは <%= link_to "新しい版", "/users" %> が 動かない一部のブラウザのために暫定的に残してあるページです。新しい版では表示速度等が改善されています。

<table id="sTable_old" class="table table-bordered table-hover table-condensed display compact">
  <thead>
  <tr class="gray">
    <th>ユーザID</th>
    <th>ユーザ名</th>
    <th>DM スキル</th>
    <th>GF スキル</th>
    <th>最終更新時刻(DM)</th>
    <th>最終更新時刻(GF)</th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
      <tr class="black">
        <% skillcolor_d = get_skillcolor_light(user.d) %>
        <% skillcolor_g = get_skillcolor_light(user.g) %>
        <% skillcolor = (user.d > user.g) ? skillcolor_d : skillcolor_g %>
        <td><%= user.id %></td>
        <td>
          <div class=<%= skillcolor %>><%= link_to user.name, user, :target => ["_blank"] %></div>
        </td>
        <td>
          <div class=<%= skillcolor_d %>><%= (link_to user.d, drum_user_path(user.id), :target => ["_blank"]) if user.d > 0.0 %></div>
        </td>
        <td>
          <div class=<%= skillcolor_g %>><%= (link_to user.g, guitar_user_path(user.id), :target => ["_blank"]) if user.g > 0.0 %></div>
        </td>
        <td><%= user.skill_updated_at_d %></td>
        <td><%= user.skill_updated_at_g %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/re_users/manage.html.erb
<h1>スキルを読み込む</h1>

<%= form_tag(import_user_path, :method => :post, multipart: true) do %>
    <div class="form-group">
      <%= file_field_tag :csv_file %>
    </div>
    <%= submit_tag "CSVインポート", :class => "btn btn-primary" %>
<% end %>

<h1>スキルを書き出す</h1>
<%= link_to "CSVエクスポート", user_path(format: "csv"), :class => "btn btn-success" %>

app/views/re_users/new.html.erb
<!-- devise に移行したため削除しました -->

app/views/re_users/show.html.erb
<% provide(:title, "#{@user.name} さんのスキル") %>
<h1>
  <%= @user.name %> さんのスキル
</h1>

<% if current_user == @user %>
    <div class="well">
      公開用URLは http://tri.gfdm-skill.net<%= drum_re_user_path %> (Drummania) と
      http://tri.gfdm-skill.net<%= guitar_re_user_path %> (GuitarFreaks) です．
    </div>
<% end %>

<h2><%= link_to "Drummania のスキル表へ", drum_re_user_path %></h2>

<%= render partial: 'sptable', locals: {sp: @user.d, hot: @user.dhot, other: @user.dother, all: @user.dall, updated_at: @user.skill_updated_at_d} %>

<h2><%= link_to "GuitarFreaks のスキル表へ", guitar_re_user_path %></h2>

<%= render partial: 'sptable', locals: {sp: @user.g, hot: @user.ghot, other: @user.gother, all: @user.gall, updated_at: @user.skill_updated_at_g} %>